// Generated by Gopher template. PLEASE EDIT :3
package test_test

import (
	"testing"
)

func TestA(t *testing.T) {
  t.Parallel()

  var tests = []struct{
    Name string
  }{
    {
      Name: "Example name",
    },
  }

  for i := range tests {
    var test = tests[i]

    t.Run(test.Name, func(tt *testing.T) {
      tt.Parallel()

      // Do something! 
    })
  }
}

func TestB(t *testing.T) {
  t.Parallel()

  var tests = []struct{
    Name string
  }{
    {
      Name: "Example name",
    },
  }

  for i := range tests {
    var test = tests[i]

    t.Run(test.Name, func(tt *testing.T) {
      tt.Parallel()

      // Do something! 
    })
  }
}

func TestC(t *testing.T) {
  t.Parallel()

  var tests = []struct{
    Name string
  }{
    {
      Name: "Example name",
    },
  }

  for i := range tests {
    var test = tests[i]

    t.Run(test.Name, func(tt *testing.T) {
      tt.Parallel()

      // Do something! 
    })
  }
}
